@startgantt

Project starts 2023-02-15

[Testing] starts 2023-02-15
[Testing] lasts 30 days
[Continuous Integration] starts 2023-03-01
[Continuous Integration] lasts 16 days
[Change Report] starts 2023-03-03
[Change Report] lasts 14 days
[Implementation] starts 2023-03-16
[Implementation] lasts 1 day

[Unit Testing] on {Emma:20%} {Isaac:20%} {Toby:20%} {Seungyoon:20%} {Isioma:20%} starts 2023-02-15 and ends 2023-03-16 and is colored in LightYellow/Maroon
[Manual Testing] on {Emma:20%} {Isaac:20%} {Toby:20%} {Seungyoon:20%} {Isioma:20%} starts 2023-03-08 and ends 2023-03-16 and is colored in LightYellow/Maroon


[Requirements] on {Emma:100%} starts 2023-03-03 and ends 2023-03-16 and is colored in LightGreen/DarkGreen
[Risk Assessment] on {Emma:100%} starts 2023-03-03 and ends 2023-03-16 and is colored in LightGreen/DarkGreen
[Architecture] on {Isioma:100%} starts 2023-03-16 and ends 2023-03-16 and is colored in LightGreen/DarkGreen

[Set up CI] on {Toby:100%} starts 2023-03-01 and ends 2023-03-02 and is colored in LightBlue/DarkBlue
[Write up part b] on {Seungyoon:100%} starts 2023-03-08 and ends 2023-03-15 and is colored in LightBlue/DarkBlue

[Set up game spec] on {Emma:100%} starts 2023-03-16 and ends 2023-03-16 and is colored in Pink/Salmon
[Fix Memory Leak] on {Toby:100%} starts 2023-03-16 and ends 2023-03-16 and is colored in Pink/Salmon
[Draw Sprites] on {Isaac:100%} starts 2023-03-16 and ends 2023-03-16 and is colored in Pink/Salmon
@endgantt