@startgantt

Project starts 2023-02-15

[Testing] starts 2023-02-15
[Testing] lasts 7 days

[Unit Testing] on {Emma:20%} {Isaac:20%} {Toby:20%} {Seungyoon:20%} {Isioma:20%} starts 2023-02-15 and ends 2023-02-21 and is colored in LightYellow/Maroon

@endgantt